# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

turf_m_c <- function(mat, m, keep = 10L, w = NULL) {
    .Call('_turf_turf_m_c', PACKAGE = 'turf', mat, m, keep, w)
}

